export default {
    sounds: {
        Introduction1: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-1.mp3'),
        Introduction2: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-2.mp3'),
        Introduction3: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-3.mp3'),
        Introduction4: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-4.mp3'),
        Introduction5: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-5.mp3'),
        Introduction6: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-6.mp3'),
        Introduction7: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-7.mp3'),
        Introduction8: new AudioClip('sounds/kbhomes-npc-dialog-extended/Introduction/INTRO-8M.mp3'),
        //Script1
        Script1_1: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-1.mp3'),
        Script1_2_choice_contemporary: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 CHOICE CONTEMPORARY.mp3'),
        Script1_2_choice_craftsman: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 CHOICE CRAFTSMAN.mp3'),
        Script1_2_choice_farmhouse: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 CHOICE FARMHOUSE.mp3'),
        Script1_2_choice_spanish: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 CHOICE SPANISH.mp3'),
        Script1_2_contemporary: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 CONTEMPORARY.mp3'),
        Script1_2_craftsman: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 CRAFTSMAN.mp3'),
        Script1_2_farmhouse: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 FARMHOUSE.mp3'),
        Script1_2_favorite: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 FAVORITE.mp3'),
        Script1_2_spanish: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2 SPANISH.mp3'),
        Script1_2: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-2.mp3'),
        Script1_3: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-3.mp3'),
        Script1_4: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-4.mp3'),
        Script1_5: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-5.mp3'),
        Script1_6: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-6.mp3'),
        Script1_7: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-7.mp3'),
        Script1_8: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-8.mp3'),
        Script1_9: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-9.mp3'),
        Script1_10: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-10.mp3'),
        Script1_11_1860: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-11-1860.mp3'),
        Script1_11_1989: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-11-1989.mp3'),
        Script1_11_2345: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-11-2345.mp3'),
        Script1_11_floorplan: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-11-FLOORPLAN.mp3'),
        Script1_12: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-12.mp3'),
        Script1_13: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-13.mp3'),
        Script1_14: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-14.mp3'),
        Script1_15: new AudioClip('sounds/kbhomes-npc-dialog-extended/Script1/SCRIPT1-15.mp3'),
        //Script2
        Script2_14: new AudioClip("sounds/kbhomes-npc-dialog-extended/Script2/SCRIPT2-14.mp3"),
    }
}
